#!/usr/bin/python3
"""
class Square: a class Square that defines a square
"""


class Square:
    """
    A square class that shows private instance attribute
    """

    def __init__(self, size=0):
        if type(size) is not int:
            raise TypeError("size must be an integer")
        if size < 0:
            raise ValueError("size must be >= 0")
        self.__size = size

    def __init__(self, length):
        self.length = length

        def area(self):
            return self.length ** 2



my_square_1 = Square(3)
print("Area: {}".format(my_square_1.area()))


